name: Lint PR Title

on:
  pull_request_target:
    types: [edited, opened, reopened, synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Force checkout the main repo (base branch) so that repo secrets
          # are not available to unexpected/malicious PR code.
          ref: main

      - uses: ./.github/actions/setup-js-env

      - name: Run Lint Script
        run: |
          node .github/scripts/lint-pr-title.cjs
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
